services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=${MONGODB_URI}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
